# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import services_pb2 as services__pb2


class GrpcServicesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PostAssignRoles = channel.unary_unary(
        '/GrpcServices/PostAssignRoles',
        request_serializer=services__pb2.AssignRoles.SerializeToString,
        response_deserializer=services__pb2.AssignRolesResponse.FromString,
        )
    self.OptionsAuthenticate = channel.unary_unary(
        '/GrpcServices/OptionsAuthenticate',
        request_serializer=services__pb2.Authenticate.SerializeToString,
        response_deserializer=services__pb2.AuthenticateResponse.FromString,
        )
    self.GetAuthenticate = channel.unary_unary(
        '/GrpcServices/GetAuthenticate',
        request_serializer=services__pb2.Authenticate.SerializeToString,
        response_deserializer=services__pb2.AuthenticateResponse.FromString,
        )
    self.PostAuthenticate = channel.unary_unary(
        '/GrpcServices/PostAuthenticate',
        request_serializer=services__pb2.Authenticate.SerializeToString,
        response_deserializer=services__pb2.AuthenticateResponse.FromString,
        )
    self.DeleteAuthenticate = channel.unary_unary(
        '/GrpcServices/DeleteAuthenticate',
        request_serializer=services__pb2.Authenticate.SerializeToString,
        response_deserializer=services__pb2.AuthenticateResponse.FromString,
        )
    self.PostConvertSessionToToken = channel.unary_unary(
        '/GrpcServices/PostConvertSessionToToken',
        request_serializer=services__pb2.ConvertSessionToToken.SerializeToString,
        response_deserializer=services__pb2.ConvertSessionToTokenResponse.FromString,
        )
    self.PostCreateTodo = channel.unary_unary(
        '/GrpcServices/PostCreateTodo',
        request_serializer=services__pb2.CreateTodo.SerializeToString,
        response_deserializer=services__pb2.CreateTodoResponse.FromString,
        )
    self.CallDeleteTodo = channel.unary_unary(
        '/GrpcServices/CallDeleteTodo',
        request_serializer=services__pb2.DeleteTodo.SerializeToString,
        response_deserializer=services__pb2.EmptyResponse.FromString,
        )
    self.CallDeleteTodos = channel.unary_unary(
        '/GrpcServices/CallDeleteTodos',
        request_serializer=services__pb2.DeleteTodos.SerializeToString,
        response_deserializer=services__pb2.EmptyResponse.FromString,
        )
    self.PostGetAccessToken = channel.unary_unary(
        '/GrpcServices/PostGetAccessToken',
        request_serializer=services__pb2.GetAccessToken.SerializeToString,
        response_deserializer=services__pb2.GetAccessTokenResponse.FromString,
        )
    self.CallGetTodo = channel.unary_unary(
        '/GrpcServices/CallGetTodo',
        request_serializer=services__pb2.GetTodo.SerializeToString,
        response_deserializer=services__pb2.GetTodoResponse.FromString,
        )
    self.CallGetTodos = channel.unary_unary(
        '/GrpcServices/CallGetTodos',
        request_serializer=services__pb2.GetTodos.SerializeToString,
        response_deserializer=services__pb2.GetTodosResponse.FromString,
        )
    self.GetHello = channel.unary_unary(
        '/GrpcServices/GetHello',
        request_serializer=services__pb2.Hello.SerializeToString,
        response_deserializer=services__pb2.HelloResponse.FromString,
        )
    self.PostHello = channel.unary_unary(
        '/GrpcServices/PostHello',
        request_serializer=services__pb2.Hello.SerializeToString,
        response_deserializer=services__pb2.HelloResponse.FromString,
        )
    self.PutHello = channel.unary_unary(
        '/GrpcServices/PutHello',
        request_serializer=services__pb2.Hello.SerializeToString,
        response_deserializer=services__pb2.HelloResponse.FromString,
        )
    self.DeleteHello = channel.unary_unary(
        '/GrpcServices/DeleteHello',
        request_serializer=services__pb2.Hello.SerializeToString,
        response_deserializer=services__pb2.HelloResponse.FromString,
        )
    self.PatchHello = channel.unary_unary(
        '/GrpcServices/PatchHello',
        request_serializer=services__pb2.Hello.SerializeToString,
        response_deserializer=services__pb2.HelloResponse.FromString,
        )
    self.GetHelloSecure = channel.unary_unary(
        '/GrpcServices/GetHelloSecure',
        request_serializer=services__pb2.HelloSecure.SerializeToString,
        response_deserializer=services__pb2.HelloResponse.FromString,
        )
    self.PostHelloSecure = channel.unary_unary(
        '/GrpcServices/PostHelloSecure',
        request_serializer=services__pb2.HelloSecure.SerializeToString,
        response_deserializer=services__pb2.HelloResponse.FromString,
        )
    self.PutHelloSecure = channel.unary_unary(
        '/GrpcServices/PutHelloSecure',
        request_serializer=services__pb2.HelloSecure.SerializeToString,
        response_deserializer=services__pb2.HelloResponse.FromString,
        )
    self.DeleteHelloSecure = channel.unary_unary(
        '/GrpcServices/DeleteHelloSecure',
        request_serializer=services__pb2.HelloSecure.SerializeToString,
        response_deserializer=services__pb2.HelloResponse.FromString,
        )
    self.PatchHelloSecure = channel.unary_unary(
        '/GrpcServices/PatchHelloSecure',
        request_serializer=services__pb2.HelloSecure.SerializeToString,
        response_deserializer=services__pb2.HelloResponse.FromString,
        )
    self.PutRegister = channel.unary_unary(
        '/GrpcServices/PutRegister',
        request_serializer=services__pb2.Register.SerializeToString,
        response_deserializer=services__pb2.RegisterResponse.FromString,
        )
    self.PostRegister = channel.unary_unary(
        '/GrpcServices/PostRegister',
        request_serializer=services__pb2.Register.SerializeToString,
        response_deserializer=services__pb2.RegisterResponse.FromString,
        )
    self.PostResetTodos = channel.unary_unary(
        '/GrpcServices/PostResetTodos',
        request_serializer=services__pb2.ResetTodos.SerializeToString,
        response_deserializer=services__pb2.EmptyResponse.FromString,
        )
    self.ServerStreamFiles = channel.unary_stream(
        '/GrpcServices/ServerStreamFiles',
        request_serializer=services__pb2.StreamFiles.SerializeToString,
        response_deserializer=services__pb2.FileContent.FromString,
        )
    self.ServerStreamServerEvents = channel.unary_stream(
        '/GrpcServices/ServerStreamServerEvents',
        request_serializer=services__pb2.StreamServerEvents.SerializeToString,
        response_deserializer=services__pb2.StreamServerEventsResponse.FromString,
        )
    self.PostUnAssignRoles = channel.unary_unary(
        '/GrpcServices/PostUnAssignRoles',
        request_serializer=services__pb2.UnAssignRoles.SerializeToString,
        response_deserializer=services__pb2.UnAssignRolesResponse.FromString,
        )
    self.PutUpdateTodo = channel.unary_unary(
        '/GrpcServices/PutUpdateTodo',
        request_serializer=services__pb2.UpdateTodo.SerializeToString,
        response_deserializer=services__pb2.EmptyResponse.FromString,
        )


class GrpcServicesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PostAssignRoles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OptionsAuthenticate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAuthenticate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostAuthenticate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteAuthenticate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostConvertSessionToToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostCreateTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallDeleteTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallDeleteTodos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostGetAccessToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallGetTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallGetTodos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PutHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PatchHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHelloSecure(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostHelloSecure(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PutHelloSecure(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteHelloSecure(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PatchHelloSecure(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PutRegister(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostRegister(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostResetTodos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ServerStreamFiles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ServerStreamServerEvents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostUnAssignRoles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PutUpdateTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GrpcServicesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PostAssignRoles': grpc.unary_unary_rpc_method_handler(
          servicer.PostAssignRoles,
          request_deserializer=services__pb2.AssignRoles.FromString,
          response_serializer=services__pb2.AssignRolesResponse.SerializeToString,
      ),
      'OptionsAuthenticate': grpc.unary_unary_rpc_method_handler(
          servicer.OptionsAuthenticate,
          request_deserializer=services__pb2.Authenticate.FromString,
          response_serializer=services__pb2.AuthenticateResponse.SerializeToString,
      ),
      'GetAuthenticate': grpc.unary_unary_rpc_method_handler(
          servicer.GetAuthenticate,
          request_deserializer=services__pb2.Authenticate.FromString,
          response_serializer=services__pb2.AuthenticateResponse.SerializeToString,
      ),
      'PostAuthenticate': grpc.unary_unary_rpc_method_handler(
          servicer.PostAuthenticate,
          request_deserializer=services__pb2.Authenticate.FromString,
          response_serializer=services__pb2.AuthenticateResponse.SerializeToString,
      ),
      'DeleteAuthenticate': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteAuthenticate,
          request_deserializer=services__pb2.Authenticate.FromString,
          response_serializer=services__pb2.AuthenticateResponse.SerializeToString,
      ),
      'PostConvertSessionToToken': grpc.unary_unary_rpc_method_handler(
          servicer.PostConvertSessionToToken,
          request_deserializer=services__pb2.ConvertSessionToToken.FromString,
          response_serializer=services__pb2.ConvertSessionToTokenResponse.SerializeToString,
      ),
      'PostCreateTodo': grpc.unary_unary_rpc_method_handler(
          servicer.PostCreateTodo,
          request_deserializer=services__pb2.CreateTodo.FromString,
          response_serializer=services__pb2.CreateTodoResponse.SerializeToString,
      ),
      'CallDeleteTodo': grpc.unary_unary_rpc_method_handler(
          servicer.CallDeleteTodo,
          request_deserializer=services__pb2.DeleteTodo.FromString,
          response_serializer=services__pb2.EmptyResponse.SerializeToString,
      ),
      'CallDeleteTodos': grpc.unary_unary_rpc_method_handler(
          servicer.CallDeleteTodos,
          request_deserializer=services__pb2.DeleteTodos.FromString,
          response_serializer=services__pb2.EmptyResponse.SerializeToString,
      ),
      'PostGetAccessToken': grpc.unary_unary_rpc_method_handler(
          servicer.PostGetAccessToken,
          request_deserializer=services__pb2.GetAccessToken.FromString,
          response_serializer=services__pb2.GetAccessTokenResponse.SerializeToString,
      ),
      'CallGetTodo': grpc.unary_unary_rpc_method_handler(
          servicer.CallGetTodo,
          request_deserializer=services__pb2.GetTodo.FromString,
          response_serializer=services__pb2.GetTodoResponse.SerializeToString,
      ),
      'CallGetTodos': grpc.unary_unary_rpc_method_handler(
          servicer.CallGetTodos,
          request_deserializer=services__pb2.GetTodos.FromString,
          response_serializer=services__pb2.GetTodosResponse.SerializeToString,
      ),
      'GetHello': grpc.unary_unary_rpc_method_handler(
          servicer.GetHello,
          request_deserializer=services__pb2.Hello.FromString,
          response_serializer=services__pb2.HelloResponse.SerializeToString,
      ),
      'PostHello': grpc.unary_unary_rpc_method_handler(
          servicer.PostHello,
          request_deserializer=services__pb2.Hello.FromString,
          response_serializer=services__pb2.HelloResponse.SerializeToString,
      ),
      'PutHello': grpc.unary_unary_rpc_method_handler(
          servicer.PutHello,
          request_deserializer=services__pb2.Hello.FromString,
          response_serializer=services__pb2.HelloResponse.SerializeToString,
      ),
      'DeleteHello': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteHello,
          request_deserializer=services__pb2.Hello.FromString,
          response_serializer=services__pb2.HelloResponse.SerializeToString,
      ),
      'PatchHello': grpc.unary_unary_rpc_method_handler(
          servicer.PatchHello,
          request_deserializer=services__pb2.Hello.FromString,
          response_serializer=services__pb2.HelloResponse.SerializeToString,
      ),
      'GetHelloSecure': grpc.unary_unary_rpc_method_handler(
          servicer.GetHelloSecure,
          request_deserializer=services__pb2.HelloSecure.FromString,
          response_serializer=services__pb2.HelloResponse.SerializeToString,
      ),
      'PostHelloSecure': grpc.unary_unary_rpc_method_handler(
          servicer.PostHelloSecure,
          request_deserializer=services__pb2.HelloSecure.FromString,
          response_serializer=services__pb2.HelloResponse.SerializeToString,
      ),
      'PutHelloSecure': grpc.unary_unary_rpc_method_handler(
          servicer.PutHelloSecure,
          request_deserializer=services__pb2.HelloSecure.FromString,
          response_serializer=services__pb2.HelloResponse.SerializeToString,
      ),
      'DeleteHelloSecure': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteHelloSecure,
          request_deserializer=services__pb2.HelloSecure.FromString,
          response_serializer=services__pb2.HelloResponse.SerializeToString,
      ),
      'PatchHelloSecure': grpc.unary_unary_rpc_method_handler(
          servicer.PatchHelloSecure,
          request_deserializer=services__pb2.HelloSecure.FromString,
          response_serializer=services__pb2.HelloResponse.SerializeToString,
      ),
      'PutRegister': grpc.unary_unary_rpc_method_handler(
          servicer.PutRegister,
          request_deserializer=services__pb2.Register.FromString,
          response_serializer=services__pb2.RegisterResponse.SerializeToString,
      ),
      'PostRegister': grpc.unary_unary_rpc_method_handler(
          servicer.PostRegister,
          request_deserializer=services__pb2.Register.FromString,
          response_serializer=services__pb2.RegisterResponse.SerializeToString,
      ),
      'PostResetTodos': grpc.unary_unary_rpc_method_handler(
          servicer.PostResetTodos,
          request_deserializer=services__pb2.ResetTodos.FromString,
          response_serializer=services__pb2.EmptyResponse.SerializeToString,
      ),
      'ServerStreamFiles': grpc.unary_stream_rpc_method_handler(
          servicer.ServerStreamFiles,
          request_deserializer=services__pb2.StreamFiles.FromString,
          response_serializer=services__pb2.FileContent.SerializeToString,
      ),
      'ServerStreamServerEvents': grpc.unary_stream_rpc_method_handler(
          servicer.ServerStreamServerEvents,
          request_deserializer=services__pb2.StreamServerEvents.FromString,
          response_serializer=services__pb2.StreamServerEventsResponse.SerializeToString,
      ),
      'PostUnAssignRoles': grpc.unary_unary_rpc_method_handler(
          servicer.PostUnAssignRoles,
          request_deserializer=services__pb2.UnAssignRoles.FromString,
          response_serializer=services__pb2.UnAssignRolesResponse.SerializeToString,
      ),
      'PutUpdateTodo': grpc.unary_unary_rpc_method_handler(
          servicer.PutUpdateTodo,
          request_deserializer=services__pb2.UpdateTodo.FromString,
          response_serializer=services__pb2.EmptyResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GrpcServices', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
