# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("services.proto", :syntax => :proto3) do
    add_message "AssignRoles" do
      optional :UserName, :string, 1
      repeated :Permissions, :string, 2
      repeated :Roles, :string, 3
      map :Meta, :string, :string, 4
    end
    add_message "AssignRolesResponse" do
      repeated :AllRoles, :string, 1
      repeated :AllPermissions, :string, 2
      map :Meta, :string, :string, 3
      optional :ResponseStatus, :message, 4, "ResponseStatus"
    end
    add_message "Authenticate" do
      optional :provider, :string, 1
      optional :State, :string, 2
      optional :oauth_token, :string, 3
      optional :oauth_verifier, :string, 4
      optional :UserName, :string, 5
      optional :Password, :string, 6
      optional :RememberMe, :bool, 7
      optional :Continue, :string, 8
      optional :ErrorView, :string, 9
      optional :nonce, :string, 10
      optional :uri, :string, 11
      optional :response, :string, 12
      optional :qop, :string, 13
      optional :nc, :string, 14
      optional :cnonce, :string, 15
      optional :UseTokenCookie, :bool, 16
      optional :AccessToken, :string, 17
      optional :AccessTokenSecret, :string, 18
      optional :scope, :string, 19
      map :Meta, :string, :string, 20
    end
    add_message "AuthenticateResponse" do
      optional :UserId, :string, 1
      optional :SessionId, :string, 2
      optional :UserName, :string, 3
      optional :DisplayName, :string, 4
      optional :ReferrerUrl, :string, 5
      optional :BearerToken, :string, 6
      optional :RefreshToken, :string, 7
      optional :ProfileUrl, :string, 8
      repeated :Roles, :string, 9
      repeated :Permissions, :string, 10
      optional :ResponseStatus, :message, 11, "ResponseStatus"
      map :Meta, :string, :string, 12
    end
    add_message "ConvertSessionToToken" do
      optional :PreserveSession, :bool, 1
      map :Meta, :string, :string, 2
    end
    add_message "ConvertSessionToTokenResponse" do
      map :Meta, :string, :string, 1
      optional :AccessToken, :string, 2
      optional :RefreshToken, :string, 3
      optional :ResponseStatus, :message, 4, "ResponseStatus"
    end
    add_message "CreateTodo" do
      optional :Title, :string, 1
      optional :Order, :int32, 2
    end
    add_message "CreateTodoResponse" do
      optional :Result, :message, 1, "Todo"
      optional :ResponseStatus, :message, 2, "ResponseStatus"
    end
    add_message "DeleteTodo" do
      optional :Id, :int64, 1
    end
    add_message "DeleteTodos" do
      repeated :Ids, :int64, 1
    end
    add_message "EmptyResponse" do
      optional :ResponseStatus, :message, 1, "ResponseStatus"
    end
    add_message "FileContent" do
      optional :Name, :string, 1
      optional :Type, :string, 2
      optional :Length, :int32, 3
      optional :Body, :bytes, 4
      optional :ResponseStatus, :message, 5, "ResponseStatus"
    end
    add_message "GetAccessToken" do
      optional :RefreshToken, :string, 1
      optional :UseTokenCookie, :bool, 2
      map :Meta, :string, :string, 3
    end
    add_message "GetAccessTokenResponse" do
      optional :AccessToken, :string, 1
      map :Meta, :string, :string, 2
      optional :ResponseStatus, :message, 3, "ResponseStatus"
    end
    add_message "GetTodo" do
      optional :Id, :int64, 1
    end
    add_message "GetTodoResponse" do
      optional :Result, :message, 1, "Todo"
      optional :ResponseStatus, :message, 2, "ResponseStatus"
    end
    add_message "GetTodos" do
    end
    add_message "GetTodosResponse" do
      repeated :Results, :message, 1, "Todo"
      optional :ResponseStatus, :message, 2, "ResponseStatus"
    end
    add_message "Hello" do
      optional :Name, :string, 1
    end
    add_message "HelloResponse" do
      optional :Result, :string, 1
      optional :ResponseStatus, :message, 2, "ResponseStatus"
    end
    add_message "HelloSecure" do
      optional :Name, :string, 1
    end
    add_message "Register" do
      optional :UserName, :string, 1
      optional :FirstName, :string, 2
      optional :LastName, :string, 3
      optional :DisplayName, :string, 4
      optional :Email, :string, 5
      optional :Password, :string, 6
      optional :ConfirmPassword, :string, 7
      optional :AutoLogin, :bool, 8
      optional :Continue, :string, 9
      optional :ErrorView, :string, 10
      map :Meta, :string, :string, 11
    end
    add_message "RegisterResponse" do
      optional :UserId, :string, 1
      optional :SessionId, :string, 2
      optional :UserName, :string, 3
      optional :ReferrerUrl, :string, 4
      optional :BearerToken, :string, 5
      optional :RefreshToken, :string, 6
      optional :ResponseStatus, :message, 7, "ResponseStatus"
      map :Meta, :string, :string, 8
    end
    add_message "ResetTodos" do
    end
    add_message "ResponseError" do
      optional :ErrorCode, :string, 1
      optional :FieldName, :string, 2
      optional :Message, :string, 3
      map :Meta, :string, :string, 4
    end
    add_message "ResponseStatus" do
      optional :ErrorCode, :string, 1
      optional :Message, :string, 2
      optional :StackTrace, :string, 3
      repeated :Errors, :message, 4, "ResponseError"
      map :Meta, :string, :string, 5
    end
    add_message "StreamFiles" do
      repeated :Paths, :string, 1
    end
    add_message "StreamServerEvents" do
      repeated :Channels, :string, 1
    end
    add_message "StreamServerEventsResponse" do
      optional :EventId, :int64, 1
      optional :Channel, :string, 2
      optional :Selector, :string, 4
      optional :Json, :string, 5
      optional :Op, :string, 6
      optional :Target, :string, 7
      optional :CssSelector, :string, 8
      map :Meta, :string, :string, 9
      optional :UserId, :string, 10
      optional :DisplayName, :string, 11
      optional :ProfileUrl, :string, 12
      optional :IsAuthenticated, :bool, 13
      repeated :Channels, :string, 14
      optional :CreatedAt, :int64, 15
      optional :Id, :string, 21
      optional :UnRegisterUrl, :string, 22
      optional :UpdateSubscriberUrl, :string, 23
      optional :HeartbeatUrl, :string, 24
      optional :HeartbeatIntervalMs, :int64, 25
      optional :IdleTimeoutMs, :int64, 26
      optional :ResponseStatus, :message, 30, "ResponseStatus"
    end
    add_message "Todo" do
      optional :Id, :int64, 1
      optional :Title, :string, 2
      optional :Order, :int32, 3
      optional :Completed, :bool, 4
    end
    add_message "UnAssignRoles" do
      optional :UserName, :string, 1
      repeated :Permissions, :string, 2
      repeated :Roles, :string, 3
      map :Meta, :string, :string, 4
    end
    add_message "UnAssignRolesResponse" do
      repeated :AllRoles, :string, 1
      repeated :AllPermissions, :string, 2
      map :Meta, :string, :string, 3
      optional :ResponseStatus, :message, 4, "ResponseStatus"
    end
    add_message "UpdateTodo" do
      optional :Id, :int64, 1
      optional :Title, :string, 2
      optional :Order, :int32, 3
      optional :Completed, :bool, 4
    end
  end
end

AssignRoles = Google::Protobuf::DescriptorPool.generated_pool.lookup("AssignRoles").msgclass
AssignRolesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("AssignRolesResponse").msgclass
Authenticate = Google::Protobuf::DescriptorPool.generated_pool.lookup("Authenticate").msgclass
AuthenticateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("AuthenticateResponse").msgclass
ConvertSessionToToken = Google::Protobuf::DescriptorPool.generated_pool.lookup("ConvertSessionToToken").msgclass
ConvertSessionToTokenResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ConvertSessionToTokenResponse").msgclass
CreateTodo = Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateTodo").msgclass
CreateTodoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateTodoResponse").msgclass
DeleteTodo = Google::Protobuf::DescriptorPool.generated_pool.lookup("DeleteTodo").msgclass
DeleteTodos = Google::Protobuf::DescriptorPool.generated_pool.lookup("DeleteTodos").msgclass
EmptyResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("EmptyResponse").msgclass
FileContent = Google::Protobuf::DescriptorPool.generated_pool.lookup("FileContent").msgclass
GetAccessToken = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAccessToken").msgclass
GetAccessTokenResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAccessTokenResponse").msgclass
GetTodo = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetTodo").msgclass
GetTodoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetTodoResponse").msgclass
GetTodos = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetTodos").msgclass
GetTodosResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetTodosResponse").msgclass
Hello = Google::Protobuf::DescriptorPool.generated_pool.lookup("Hello").msgclass
HelloResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("HelloResponse").msgclass
HelloSecure = Google::Protobuf::DescriptorPool.generated_pool.lookup("HelloSecure").msgclass
Register = Google::Protobuf::DescriptorPool.generated_pool.lookup("Register").msgclass
RegisterResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("RegisterResponse").msgclass
ResetTodos = Google::Protobuf::DescriptorPool.generated_pool.lookup("ResetTodos").msgclass
ResponseError = Google::Protobuf::DescriptorPool.generated_pool.lookup("ResponseError").msgclass
ResponseStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("ResponseStatus").msgclass
StreamFiles = Google::Protobuf::DescriptorPool.generated_pool.lookup("StreamFiles").msgclass
StreamServerEvents = Google::Protobuf::DescriptorPool.generated_pool.lookup("StreamServerEvents").msgclass
StreamServerEventsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("StreamServerEventsResponse").msgclass
Todo = Google::Protobuf::DescriptorPool.generated_pool.lookup("Todo").msgclass
UnAssignRoles = Google::Protobuf::DescriptorPool.generated_pool.lookup("UnAssignRoles").msgclass
UnAssignRolesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("UnAssignRolesResponse").msgclass
UpdateTodo = Google::Protobuf::DescriptorPool.generated_pool.lookup("UpdateTodo").msgclass
