name: todoworld
description: A sample Dart gRPC TodoWorld Client
# version: 1.0.0
# homepage: https://www.example.com
# author: Demis Bellot <demis.bellot@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  fixnum: ^0.10.11
  async: ^2.2.0
  protobuf: ^1.0.1
  grpc: ^2.1.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
