<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

namespace TodoWorld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FileContent</code>
 */
class FileContent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     */
    private $Name = '';
    /**
     * Generated from protobuf field <code>string Type = 2;</code>
     */
    private $Type = '';
    /**
     * Generated from protobuf field <code>int32 Length = 3;</code>
     */
    private $Length = 0;
    /**
     * Generated from protobuf field <code>bytes Body = 4;</code>
     */
    private $Body = '';
    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 5;</code>
     */
    private $ResponseStatus = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Name
     *     @type string $Type
     *     @type int $Length
     *     @type string $Body
     *     @type \TodoWorld\ResponseStatus $ResponseStatus
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Type = 2;</code>
     * @return string
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>string Type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Length = 3;</code>
     * @return int
     */
    public function getLength()
    {
        return $this->Length;
    }

    /**
     * Generated from protobuf field <code>int32 Length = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLength($var)
    {
        GPBUtil::checkInt32($var);
        $this->Length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Body = 4;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->Body;
    }

    /**
     * Generated from protobuf field <code>bytes Body = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->Body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 5;</code>
     * @return \TodoWorld\ResponseStatus
     */
    public function getResponseStatus()
    {
        return $this->ResponseStatus;
    }

    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 5;</code>
     * @param \TodoWorld\ResponseStatus $var
     * @return $this
     */
    public function setResponseStatus($var)
    {
        GPBUtil::checkMessage($var, \TodoWorld\ResponseStatus::class);
        $this->ResponseStatus = $var;

        return $this;
    }

}

