<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

namespace TodoWorld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ResponseStatus</code>
 */
class ResponseStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ErrorCode = 1;</code>
     */
    private $ErrorCode = '';
    /**
     * Generated from protobuf field <code>string Message = 2;</code>
     */
    private $Message = '';
    /**
     * Generated from protobuf field <code>string StackTrace = 3;</code>
     */
    private $StackTrace = '';
    /**
     * Generated from protobuf field <code>repeated .ResponseError Errors = 4;</code>
     */
    private $Errors;
    /**
     * Generated from protobuf field <code>map<string, string> Meta = 5;</code>
     */
    private $Meta;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ErrorCode
     *     @type string $Message
     *     @type string $StackTrace
     *     @type \TodoWorld\ResponseError[]|\Google\Protobuf\Internal\RepeatedField $Errors
     *     @type array|\Google\Protobuf\Internal\MapField $Meta
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ErrorCode = 1;</code>
     * @return string
     */
    public function getErrorCode()
    {
        return $this->ErrorCode;
    }

    /**
     * Generated from protobuf field <code>string ErrorCode = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrorCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->Message;
    }

    /**
     * Generated from protobuf field <code>string Message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->Message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string StackTrace = 3;</code>
     * @return string
     */
    public function getStackTrace()
    {
        return $this->StackTrace;
    }

    /**
     * Generated from protobuf field <code>string StackTrace = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStackTrace($var)
    {
        GPBUtil::checkString($var, True);
        $this->StackTrace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ResponseError Errors = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getErrors()
    {
        return $this->Errors;
    }

    /**
     * Generated from protobuf field <code>repeated .ResponseError Errors = 4;</code>
     * @param \TodoWorld\ResponseError[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \TodoWorld\ResponseError::class);
        $this->Errors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMeta()
    {
        return $this->Meta;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Meta = $arr;

        return $this;
    }

}

