<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

namespace TodoWorld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>UnAssignRolesResponse</code>
 */
class UnAssignRolesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string AllRoles = 1;</code>
     */
    private $AllRoles;
    /**
     * Generated from protobuf field <code>repeated string AllPermissions = 2;</code>
     */
    private $AllPermissions;
    /**
     * Generated from protobuf field <code>map<string, string> Meta = 3;</code>
     */
    private $Meta;
    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 4;</code>
     */
    private $ResponseStatus = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $AllRoles
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $AllPermissions
     *     @type array|\Google\Protobuf\Internal\MapField $Meta
     *     @type \TodoWorld\ResponseStatus $ResponseStatus
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string AllRoles = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllRoles()
    {
        return $this->AllRoles;
    }

    /**
     * Generated from protobuf field <code>repeated string AllRoles = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllRoles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->AllRoles = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string AllPermissions = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllPermissions()
    {
        return $this->AllPermissions;
    }

    /**
     * Generated from protobuf field <code>repeated string AllPermissions = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllPermissions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->AllPermissions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMeta()
    {
        return $this->Meta;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Meta = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 4;</code>
     * @return \TodoWorld\ResponseStatus
     */
    public function getResponseStatus()
    {
        return $this->ResponseStatus;
    }

    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 4;</code>
     * @param \TodoWorld\ResponseStatus $var
     * @return $this
     */
    public function setResponseStatus($var)
    {
        GPBUtil::checkMessage($var, \TodoWorld\ResponseStatus::class);
        $this->ResponseStatus = $var;

        return $this;
    }

}

