<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

namespace TodoWorld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AuthenticateResponse</code>
 */
class AuthenticateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string UserId = 1;</code>
     */
    private $UserId = '';
    /**
     * Generated from protobuf field <code>string SessionId = 2;</code>
     */
    private $SessionId = '';
    /**
     * Generated from protobuf field <code>string UserName = 3;</code>
     */
    private $UserName = '';
    /**
     * Generated from protobuf field <code>string DisplayName = 4;</code>
     */
    private $DisplayName = '';
    /**
     * Generated from protobuf field <code>string ReferrerUrl = 5;</code>
     */
    private $ReferrerUrl = '';
    /**
     * Generated from protobuf field <code>string BearerToken = 6;</code>
     */
    private $BearerToken = '';
    /**
     * Generated from protobuf field <code>string RefreshToken = 7;</code>
     */
    private $RefreshToken = '';
    /**
     * Generated from protobuf field <code>string ProfileUrl = 8;</code>
     */
    private $ProfileUrl = '';
    /**
     * Generated from protobuf field <code>repeated string Roles = 9;</code>
     */
    private $Roles;
    /**
     * Generated from protobuf field <code>repeated string Permissions = 10;</code>
     */
    private $Permissions;
    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 11;</code>
     */
    private $ResponseStatus = null;
    /**
     * Generated from protobuf field <code>map<string, string> Meta = 12;</code>
     */
    private $Meta;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $UserId
     *     @type string $SessionId
     *     @type string $UserName
     *     @type string $DisplayName
     *     @type string $ReferrerUrl
     *     @type string $BearerToken
     *     @type string $RefreshToken
     *     @type string $ProfileUrl
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Roles
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Permissions
     *     @type \TodoWorld\ResponseStatus $ResponseStatus
     *     @type array|\Google\Protobuf\Internal\MapField $Meta
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string UserId = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->UserId;
    }

    /**
     * Generated from protobuf field <code>string UserId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SessionId = 2;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->SessionId;
    }

    /**
     * Generated from protobuf field <code>string SessionId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->SessionId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string UserName = 3;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->UserName;
    }

    /**
     * Generated from protobuf field <code>string UserName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string DisplayName = 4;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->DisplayName;
    }

    /**
     * Generated from protobuf field <code>string DisplayName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->DisplayName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ReferrerUrl = 5;</code>
     * @return string
     */
    public function getReferrerUrl()
    {
        return $this->ReferrerUrl;
    }

    /**
     * Generated from protobuf field <code>string ReferrerUrl = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setReferrerUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->ReferrerUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string BearerToken = 6;</code>
     * @return string
     */
    public function getBearerToken()
    {
        return $this->BearerToken;
    }

    /**
     * Generated from protobuf field <code>string BearerToken = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBearerToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->BearerToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string RefreshToken = 7;</code>
     * @return string
     */
    public function getRefreshToken()
    {
        return $this->RefreshToken;
    }

    /**
     * Generated from protobuf field <code>string RefreshToken = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRefreshToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->RefreshToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ProfileUrl = 8;</code>
     * @return string
     */
    public function getProfileUrl()
    {
        return $this->ProfileUrl;
    }

    /**
     * Generated from protobuf field <code>string ProfileUrl = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setProfileUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->ProfileUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string Roles = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoles()
    {
        return $this->Roles;
    }

    /**
     * Generated from protobuf field <code>repeated string Roles = 9;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Roles = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string Permissions = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPermissions()
    {
        return $this->Permissions;
    }

    /**
     * Generated from protobuf field <code>repeated string Permissions = 10;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPermissions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Permissions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 11;</code>
     * @return \TodoWorld\ResponseStatus
     */
    public function getResponseStatus()
    {
        return $this->ResponseStatus;
    }

    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 11;</code>
     * @param \TodoWorld\ResponseStatus $var
     * @return $this
     */
    public function setResponseStatus($var)
    {
        GPBUtil::checkMessage($var, \TodoWorld\ResponseStatus::class);
        $this->ResponseStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 12;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMeta()
    {
        return $this->Meta;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 12;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Meta = $arr;

        return $this;
    }

}

