<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

namespace TodoWorld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Authenticate</code>
 */
class Authenticate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string provider = 1;</code>
     */
    private $provider = '';
    /**
     * Generated from protobuf field <code>string State = 2;</code>
     */
    private $State = '';
    /**
     * Generated from protobuf field <code>string oauth_token = 3;</code>
     */
    private $oauth_token = '';
    /**
     * Generated from protobuf field <code>string oauth_verifier = 4;</code>
     */
    private $oauth_verifier = '';
    /**
     * Generated from protobuf field <code>string UserName = 5;</code>
     */
    private $UserName = '';
    /**
     * Generated from protobuf field <code>string Password = 6;</code>
     */
    private $Password = '';
    /**
     * Generated from protobuf field <code>bool RememberMe = 7;</code>
     */
    private $RememberMe = false;
    /**
     * Generated from protobuf field <code>string Continue = 8;</code>
     */
    private $Continue = '';
    /**
     * Generated from protobuf field <code>string ErrorView = 9;</code>
     */
    private $ErrorView = '';
    /**
     * Generated from protobuf field <code>string nonce = 10;</code>
     */
    private $nonce = '';
    /**
     * Generated from protobuf field <code>string uri = 11;</code>
     */
    private $uri = '';
    /**
     * Generated from protobuf field <code>string response = 12;</code>
     */
    private $response = '';
    /**
     * Generated from protobuf field <code>string qop = 13;</code>
     */
    private $qop = '';
    /**
     * Generated from protobuf field <code>string nc = 14;</code>
     */
    private $nc = '';
    /**
     * Generated from protobuf field <code>string cnonce = 15;</code>
     */
    private $cnonce = '';
    /**
     * Generated from protobuf field <code>bool UseTokenCookie = 16;</code>
     */
    private $UseTokenCookie = false;
    /**
     * Generated from protobuf field <code>string AccessToken = 17;</code>
     */
    private $AccessToken = '';
    /**
     * Generated from protobuf field <code>string AccessTokenSecret = 18;</code>
     */
    private $AccessTokenSecret = '';
    /**
     * Generated from protobuf field <code>string scope = 19;</code>
     */
    private $scope = '';
    /**
     * Generated from protobuf field <code>map<string, string> Meta = 20;</code>
     */
    private $Meta;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $provider
     *     @type string $State
     *     @type string $oauth_token
     *     @type string $oauth_verifier
     *     @type string $UserName
     *     @type string $Password
     *     @type bool $RememberMe
     *     @type string $Continue
     *     @type string $ErrorView
     *     @type string $nonce
     *     @type string $uri
     *     @type string $response
     *     @type string $qop
     *     @type string $nc
     *     @type string $cnonce
     *     @type bool $UseTokenCookie
     *     @type string $AccessToken
     *     @type string $AccessTokenSecret
     *     @type string $scope
     *     @type array|\Google\Protobuf\Internal\MapField $Meta
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string provider = 1;</code>
     * @return string
     */
    public function getProvider()
    {
        return $this->provider;
    }

    /**
     * Generated from protobuf field <code>string provider = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProvider($var)
    {
        GPBUtil::checkString($var, True);
        $this->provider = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string State = 2;</code>
     * @return string
     */
    public function getState()
    {
        return $this->State;
    }

    /**
     * Generated from protobuf field <code>string State = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkString($var, True);
        $this->State = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string oauth_token = 3;</code>
     * @return string
     */
    public function getOauthToken()
    {
        return $this->oauth_token;
    }

    /**
     * Generated from protobuf field <code>string oauth_token = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOauthToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->oauth_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string oauth_verifier = 4;</code>
     * @return string
     */
    public function getOauthVerifier()
    {
        return $this->oauth_verifier;
    }

    /**
     * Generated from protobuf field <code>string oauth_verifier = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOauthVerifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->oauth_verifier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string UserName = 5;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->UserName;
    }

    /**
     * Generated from protobuf field <code>string UserName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Password = 6;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->Password;
    }

    /**
     * Generated from protobuf field <code>string Password = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->Password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool RememberMe = 7;</code>
     * @return bool
     */
    public function getRememberMe()
    {
        return $this->RememberMe;
    }

    /**
     * Generated from protobuf field <code>bool RememberMe = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setRememberMe($var)
    {
        GPBUtil::checkBool($var);
        $this->RememberMe = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Continue = 8;</code>
     * @return string
     */
    public function getContinue()
    {
        return $this->Continue;
    }

    /**
     * Generated from protobuf field <code>string Continue = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setContinue($var)
    {
        GPBUtil::checkString($var, True);
        $this->Continue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ErrorView = 9;</code>
     * @return string
     */
    public function getErrorView()
    {
        return $this->ErrorView;
    }

    /**
     * Generated from protobuf field <code>string ErrorView = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorView($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrorView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nonce = 10;</code>
     * @return string
     */
    public function getNonce()
    {
        return $this->nonce;
    }

    /**
     * Generated from protobuf field <code>string nonce = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkString($var, True);
        $this->nonce = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uri = 11;</code>
     * @return string
     */
    public function getUri()
    {
        return $this->uri;
    }

    /**
     * Generated from protobuf field <code>string uri = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->uri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string response = 12;</code>
     * @return string
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>string response = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkString($var, True);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string qop = 13;</code>
     * @return string
     */
    public function getQop()
    {
        return $this->qop;
    }

    /**
     * Generated from protobuf field <code>string qop = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setQop($var)
    {
        GPBUtil::checkString($var, True);
        $this->qop = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nc = 14;</code>
     * @return string
     */
    public function getNc()
    {
        return $this->nc;
    }

    /**
     * Generated from protobuf field <code>string nc = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setNc($var)
    {
        GPBUtil::checkString($var, True);
        $this->nc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cnonce = 15;</code>
     * @return string
     */
    public function getCnonce()
    {
        return $this->cnonce;
    }

    /**
     * Generated from protobuf field <code>string cnonce = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setCnonce($var)
    {
        GPBUtil::checkString($var, True);
        $this->cnonce = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool UseTokenCookie = 16;</code>
     * @return bool
     */
    public function getUseTokenCookie()
    {
        return $this->UseTokenCookie;
    }

    /**
     * Generated from protobuf field <code>bool UseTokenCookie = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseTokenCookie($var)
    {
        GPBUtil::checkBool($var);
        $this->UseTokenCookie = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string AccessToken = 17;</code>
     * @return string
     */
    public function getAccessToken()
    {
        return $this->AccessToken;
    }

    /**
     * Generated from protobuf field <code>string AccessToken = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->AccessToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string AccessTokenSecret = 18;</code>
     * @return string
     */
    public function getAccessTokenSecret()
    {
        return $this->AccessTokenSecret;
    }

    /**
     * Generated from protobuf field <code>string AccessTokenSecret = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessTokenSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->AccessTokenSecret = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string scope = 19;</code>
     * @return string
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * Generated from protobuf field <code>string scope = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setScope($var)
    {
        GPBUtil::checkString($var, True);
        $this->scope = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 20;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMeta()
    {
        return $this->Meta;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 20;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Meta = $arr;

        return $this;
    }

}

