<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

namespace TodoWorld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ConvertSessionToToken</code>
 */
class ConvertSessionToToken extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool PreserveSession = 1;</code>
     */
    private $PreserveSession = false;
    /**
     * Generated from protobuf field <code>map<string, string> Meta = 2;</code>
     */
    private $Meta;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $PreserveSession
     *     @type array|\Google\Protobuf\Internal\MapField $Meta
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool PreserveSession = 1;</code>
     * @return bool
     */
    public function getPreserveSession()
    {
        return $this->PreserveSession;
    }

    /**
     * Generated from protobuf field <code>bool PreserveSession = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setPreserveSession($var)
    {
        GPBUtil::checkBool($var);
        $this->PreserveSession = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMeta()
    {
        return $this->Meta;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Meta = $arr;

        return $this;
    }

}

