<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

namespace TodoWorld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GetAccessToken</code>
 */
class GetAccessToken extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string RefreshToken = 1;</code>
     */
    private $RefreshToken = '';
    /**
     * Generated from protobuf field <code>bool UseTokenCookie = 2;</code>
     */
    private $UseTokenCookie = false;
    /**
     * Generated from protobuf field <code>map<string, string> Meta = 3;</code>
     */
    private $Meta;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $RefreshToken
     *     @type bool $UseTokenCookie
     *     @type array|\Google\Protobuf\Internal\MapField $Meta
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string RefreshToken = 1;</code>
     * @return string
     */
    public function getRefreshToken()
    {
        return $this->RefreshToken;
    }

    /**
     * Generated from protobuf field <code>string RefreshToken = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRefreshToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->RefreshToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool UseTokenCookie = 2;</code>
     * @return bool
     */
    public function getUseTokenCookie()
    {
        return $this->UseTokenCookie;
    }

    /**
     * Generated from protobuf field <code>bool UseTokenCookie = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseTokenCookie($var)
    {
        GPBUtil::checkBool($var);
        $this->UseTokenCookie = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMeta()
    {
        return $this->Meta;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Meta = $arr;

        return $this;
    }

}

