<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

namespace TodoWorld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GetTodosResponse</code>
 */
class GetTodosResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Todo Results = 1;</code>
     */
    private $Results;
    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 2;</code>
     */
    private $ResponseStatus = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \TodoWorld\Todo[]|\Google\Protobuf\Internal\RepeatedField $Results
     *     @type \TodoWorld\ResponseStatus $ResponseStatus
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Todo Results = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResults()
    {
        return $this->Results;
    }

    /**
     * Generated from protobuf field <code>repeated .Todo Results = 1;</code>
     * @param \TodoWorld\Todo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \TodoWorld\Todo::class);
        $this->Results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 2;</code>
     * @return \TodoWorld\ResponseStatus
     */
    public function getResponseStatus()
    {
        return $this->ResponseStatus;
    }

    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 2;</code>
     * @param \TodoWorld\ResponseStatus $var
     * @return $this
     */
    public function setResponseStatus($var)
    {
        GPBUtil::checkMessage($var, \TodoWorld\ResponseStatus::class);
        $this->ResponseStatus = $var;

        return $this;
    }

}

