<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

namespace TodoWorld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Register</code>
 */
class Register extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string UserName = 1;</code>
     */
    private $UserName = '';
    /**
     * Generated from protobuf field <code>string FirstName = 2;</code>
     */
    private $FirstName = '';
    /**
     * Generated from protobuf field <code>string LastName = 3;</code>
     */
    private $LastName = '';
    /**
     * Generated from protobuf field <code>string DisplayName = 4;</code>
     */
    private $DisplayName = '';
    /**
     * Generated from protobuf field <code>string Email = 5;</code>
     */
    private $Email = '';
    /**
     * Generated from protobuf field <code>string Password = 6;</code>
     */
    private $Password = '';
    /**
     * Generated from protobuf field <code>string ConfirmPassword = 7;</code>
     */
    private $ConfirmPassword = '';
    /**
     * Generated from protobuf field <code>bool AutoLogin = 8;</code>
     */
    private $AutoLogin = false;
    /**
     * Generated from protobuf field <code>string Continue = 9;</code>
     */
    private $Continue = '';
    /**
     * Generated from protobuf field <code>string ErrorView = 10;</code>
     */
    private $ErrorView = '';
    /**
     * Generated from protobuf field <code>map<string, string> Meta = 11;</code>
     */
    private $Meta;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $UserName
     *     @type string $FirstName
     *     @type string $LastName
     *     @type string $DisplayName
     *     @type string $Email
     *     @type string $Password
     *     @type string $ConfirmPassword
     *     @type bool $AutoLogin
     *     @type string $Continue
     *     @type string $ErrorView
     *     @type array|\Google\Protobuf\Internal\MapField $Meta
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string UserName = 1;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->UserName;
    }

    /**
     * Generated from protobuf field <code>string UserName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FirstName = 2;</code>
     * @return string
     */
    public function getFirstName()
    {
        return $this->FirstName;
    }

    /**
     * Generated from protobuf field <code>string FirstName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->FirstName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LastName = 3;</code>
     * @return string
     */
    public function getLastName()
    {
        return $this->LastName;
    }

    /**
     * Generated from protobuf field <code>string LastName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->LastName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string DisplayName = 4;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->DisplayName;
    }

    /**
     * Generated from protobuf field <code>string DisplayName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->DisplayName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Email = 5;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->Email;
    }

    /**
     * Generated from protobuf field <code>string Email = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->Email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Password = 6;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->Password;
    }

    /**
     * Generated from protobuf field <code>string Password = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->Password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ConfirmPassword = 7;</code>
     * @return string
     */
    public function getConfirmPassword()
    {
        return $this->ConfirmPassword;
    }

    /**
     * Generated from protobuf field <code>string ConfirmPassword = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setConfirmPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->ConfirmPassword = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool AutoLogin = 8;</code>
     * @return bool
     */
    public function getAutoLogin()
    {
        return $this->AutoLogin;
    }

    /**
     * Generated from protobuf field <code>bool AutoLogin = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setAutoLogin($var)
    {
        GPBUtil::checkBool($var);
        $this->AutoLogin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Continue = 9;</code>
     * @return string
     */
    public function getContinue()
    {
        return $this->Continue;
    }

    /**
     * Generated from protobuf field <code>string Continue = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setContinue($var)
    {
        GPBUtil::checkString($var, True);
        $this->Continue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ErrorView = 10;</code>
     * @return string
     */
    public function getErrorView()
    {
        return $this->ErrorView;
    }

    /**
     * Generated from protobuf field <code>string ErrorView = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorView($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrorView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 11;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMeta()
    {
        return $this->Meta;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 11;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Meta = $arr;

        return $this;
    }

}

