<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

namespace TodoWorld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RegisterResponse</code>
 */
class RegisterResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string UserId = 1;</code>
     */
    private $UserId = '';
    /**
     * Generated from protobuf field <code>string SessionId = 2;</code>
     */
    private $SessionId = '';
    /**
     * Generated from protobuf field <code>string UserName = 3;</code>
     */
    private $UserName = '';
    /**
     * Generated from protobuf field <code>string ReferrerUrl = 4;</code>
     */
    private $ReferrerUrl = '';
    /**
     * Generated from protobuf field <code>string BearerToken = 5;</code>
     */
    private $BearerToken = '';
    /**
     * Generated from protobuf field <code>string RefreshToken = 6;</code>
     */
    private $RefreshToken = '';
    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 7;</code>
     */
    private $ResponseStatus = null;
    /**
     * Generated from protobuf field <code>map<string, string> Meta = 8;</code>
     */
    private $Meta;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $UserId
     *     @type string $SessionId
     *     @type string $UserName
     *     @type string $ReferrerUrl
     *     @type string $BearerToken
     *     @type string $RefreshToken
     *     @type \TodoWorld\ResponseStatus $ResponseStatus
     *     @type array|\Google\Protobuf\Internal\MapField $Meta
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string UserId = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->UserId;
    }

    /**
     * Generated from protobuf field <code>string UserId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SessionId = 2;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->SessionId;
    }

    /**
     * Generated from protobuf field <code>string SessionId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->SessionId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string UserName = 3;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->UserName;
    }

    /**
     * Generated from protobuf field <code>string UserName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ReferrerUrl = 4;</code>
     * @return string
     */
    public function getReferrerUrl()
    {
        return $this->ReferrerUrl;
    }

    /**
     * Generated from protobuf field <code>string ReferrerUrl = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setReferrerUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->ReferrerUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string BearerToken = 5;</code>
     * @return string
     */
    public function getBearerToken()
    {
        return $this->BearerToken;
    }

    /**
     * Generated from protobuf field <code>string BearerToken = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBearerToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->BearerToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string RefreshToken = 6;</code>
     * @return string
     */
    public function getRefreshToken()
    {
        return $this->RefreshToken;
    }

    /**
     * Generated from protobuf field <code>string RefreshToken = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRefreshToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->RefreshToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 7;</code>
     * @return \TodoWorld\ResponseStatus
     */
    public function getResponseStatus()
    {
        return $this->ResponseStatus;
    }

    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 7;</code>
     * @param \TodoWorld\ResponseStatus $var
     * @return $this
     */
    public function setResponseStatus($var)
    {
        GPBUtil::checkMessage($var, \TodoWorld\ResponseStatus::class);
        $this->ResponseStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 8;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMeta()
    {
        return $this->Meta;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 8;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Meta = $arr;

        return $this;
    }

}

