<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

namespace TodoWorld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>StreamServerEventsResponse</code>
 */
class StreamServerEventsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 EventId = 1;</code>
     */
    private $EventId = 0;
    /**
     * Generated from protobuf field <code>string Channel = 2;</code>
     */
    private $Channel = '';
    /**
     * Generated from protobuf field <code>string Selector = 4;</code>
     */
    private $Selector = '';
    /**
     * Generated from protobuf field <code>string Json = 5;</code>
     */
    private $Json = '';
    /**
     * Generated from protobuf field <code>string Op = 6;</code>
     */
    private $Op = '';
    /**
     * Generated from protobuf field <code>string Target = 7;</code>
     */
    private $Target = '';
    /**
     * Generated from protobuf field <code>string CssSelector = 8;</code>
     */
    private $CssSelector = '';
    /**
     * Generated from protobuf field <code>map<string, string> Meta = 9;</code>
     */
    private $Meta;
    /**
     * Generated from protobuf field <code>string UserId = 10;</code>
     */
    private $UserId = '';
    /**
     * Generated from protobuf field <code>string DisplayName = 11;</code>
     */
    private $DisplayName = '';
    /**
     * Generated from protobuf field <code>string ProfileUrl = 12;</code>
     */
    private $ProfileUrl = '';
    /**
     * Generated from protobuf field <code>bool IsAuthenticated = 13;</code>
     */
    private $IsAuthenticated = false;
    /**
     * Generated from protobuf field <code>repeated string Channels = 14;</code>
     */
    private $Channels;
    /**
     * Generated from protobuf field <code>int64 CreatedAt = 15;</code>
     */
    private $CreatedAt = 0;
    /**
     * Generated from protobuf field <code>string Id = 21;</code>
     */
    private $Id = '';
    /**
     * Generated from protobuf field <code>string UnRegisterUrl = 22;</code>
     */
    private $UnRegisterUrl = '';
    /**
     * Generated from protobuf field <code>string UpdateSubscriberUrl = 23;</code>
     */
    private $UpdateSubscriberUrl = '';
    /**
     * Generated from protobuf field <code>string HeartbeatUrl = 24;</code>
     */
    private $HeartbeatUrl = '';
    /**
     * Generated from protobuf field <code>int64 HeartbeatIntervalMs = 25;</code>
     */
    private $HeartbeatIntervalMs = 0;
    /**
     * Generated from protobuf field <code>int64 IdleTimeoutMs = 26;</code>
     */
    private $IdleTimeoutMs = 0;
    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 30;</code>
     */
    private $ResponseStatus = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $EventId
     *     @type string $Channel
     *     @type string $Selector
     *     @type string $Json
     *     @type string $Op
     *     @type string $Target
     *     @type string $CssSelector
     *     @type array|\Google\Protobuf\Internal\MapField $Meta
     *     @type string $UserId
     *     @type string $DisplayName
     *     @type string $ProfileUrl
     *     @type bool $IsAuthenticated
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Channels
     *     @type int|string $CreatedAt
     *     @type string $Id
     *     @type string $UnRegisterUrl
     *     @type string $UpdateSubscriberUrl
     *     @type string $HeartbeatUrl
     *     @type int|string $HeartbeatIntervalMs
     *     @type int|string $IdleTimeoutMs
     *     @type \TodoWorld\ResponseStatus $ResponseStatus
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 EventId = 1;</code>
     * @return int|string
     */
    public function getEventId()
    {
        return $this->EventId;
    }

    /**
     * Generated from protobuf field <code>int64 EventId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEventId($var)
    {
        GPBUtil::checkInt64($var);
        $this->EventId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Channel = 2;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->Channel;
    }

    /**
     * Generated from protobuf field <code>string Channel = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->Channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Selector = 4;</code>
     * @return string
     */
    public function getSelector()
    {
        return $this->Selector;
    }

    /**
     * Generated from protobuf field <code>string Selector = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSelector($var)
    {
        GPBUtil::checkString($var, True);
        $this->Selector = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Json = 5;</code>
     * @return string
     */
    public function getJson()
    {
        return $this->Json;
    }

    /**
     * Generated from protobuf field <code>string Json = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->Json = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Op = 6;</code>
     * @return string
     */
    public function getOp()
    {
        return $this->Op;
    }

    /**
     * Generated from protobuf field <code>string Op = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setOp($var)
    {
        GPBUtil::checkString($var, True);
        $this->Op = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Target = 7;</code>
     * @return string
     */
    public function getTarget()
    {
        return $this->Target;
    }

    /**
     * Generated from protobuf field <code>string Target = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTarget($var)
    {
        GPBUtil::checkString($var, True);
        $this->Target = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CssSelector = 8;</code>
     * @return string
     */
    public function getCssSelector()
    {
        return $this->CssSelector;
    }

    /**
     * Generated from protobuf field <code>string CssSelector = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCssSelector($var)
    {
        GPBUtil::checkString($var, True);
        $this->CssSelector = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 9;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMeta()
    {
        return $this->Meta;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Meta = 9;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Meta = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string UserId = 10;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->UserId;
    }

    /**
     * Generated from protobuf field <code>string UserId = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string DisplayName = 11;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->DisplayName;
    }

    /**
     * Generated from protobuf field <code>string DisplayName = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->DisplayName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ProfileUrl = 12;</code>
     * @return string
     */
    public function getProfileUrl()
    {
        return $this->ProfileUrl;
    }

    /**
     * Generated from protobuf field <code>string ProfileUrl = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setProfileUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->ProfileUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsAuthenticated = 13;</code>
     * @return bool
     */
    public function getIsAuthenticated()
    {
        return $this->IsAuthenticated;
    }

    /**
     * Generated from protobuf field <code>bool IsAuthenticated = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAuthenticated($var)
    {
        GPBUtil::checkBool($var);
        $this->IsAuthenticated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string Channels = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChannels()
    {
        return $this->Channels;
    }

    /**
     * Generated from protobuf field <code>repeated string Channels = 14;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChannels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Channels = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 CreatedAt = 15;</code>
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->CreatedAt;
    }

    /**
     * Generated from protobuf field <code>int64 CreatedAt = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->CreatedAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Id = 21;</code>
     * @return string
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Generated from protobuf field <code>string Id = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string UnRegisterUrl = 22;</code>
     * @return string
     */
    public function getUnRegisterUrl()
    {
        return $this->UnRegisterUrl;
    }

    /**
     * Generated from protobuf field <code>string UnRegisterUrl = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setUnRegisterUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->UnRegisterUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string UpdateSubscriberUrl = 23;</code>
     * @return string
     */
    public function getUpdateSubscriberUrl()
    {
        return $this->UpdateSubscriberUrl;
    }

    /**
     * Generated from protobuf field <code>string UpdateSubscriberUrl = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateSubscriberUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->UpdateSubscriberUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string HeartbeatUrl = 24;</code>
     * @return string
     */
    public function getHeartbeatUrl()
    {
        return $this->HeartbeatUrl;
    }

    /**
     * Generated from protobuf field <code>string HeartbeatUrl = 24;</code>
     * @param string $var
     * @return $this
     */
    public function setHeartbeatUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->HeartbeatUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 HeartbeatIntervalMs = 25;</code>
     * @return int|string
     */
    public function getHeartbeatIntervalMs()
    {
        return $this->HeartbeatIntervalMs;
    }

    /**
     * Generated from protobuf field <code>int64 HeartbeatIntervalMs = 25;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHeartbeatIntervalMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->HeartbeatIntervalMs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 IdleTimeoutMs = 26;</code>
     * @return int|string
     */
    public function getIdleTimeoutMs()
    {
        return $this->IdleTimeoutMs;
    }

    /**
     * Generated from protobuf field <code>int64 IdleTimeoutMs = 26;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIdleTimeoutMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->IdleTimeoutMs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 30;</code>
     * @return \TodoWorld\ResponseStatus
     */
    public function getResponseStatus()
    {
        return $this->ResponseStatus;
    }

    /**
     * Generated from protobuf field <code>.ResponseStatus ResponseStatus = 30;</code>
     * @param \TodoWorld\ResponseStatus $var
     * @return $this
     */
    public function setResponseStatus($var)
    {
        GPBUtil::checkMessage($var, \TodoWorld\ResponseStatus::class);
        $this->ResponseStatus = $var;

        return $this;
    }

}

